config/routes.rb
Rails.application.routes.draw do
  root 'frustrations#index'
  get 'about' => 'static_pages#about'
  get 'privacy' => 'static_pages#privacy'
  resources :users, only: [ :new, :create, :show ]
  resources :sessions, only: [:new, :create]
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :frustrations, shallow: true do
    resources :comments, only: [ :create, :destroy ]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :frustration
  belongs_to :user

  validates :body, presence: true
  validates :frustration_id, presence: true
end

app/models/frustration.rb
class Frustration < ActiveRecord::Base
  belongs_to :user
  mount_uploader :cover, CoverUploader
  validates :title, presence: true
  validates :body, presence: true
  has_many  :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  has_secure_password unless: :oauth_token
  
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, unless: :oauth_token
  
  #validates :password, presence: true, unless: :oauth_token     #ne radi

  has_many :frustrations, :dependent => :destroy #:)


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = ('a'..'z').to_a.shuffle[0,16].join
      user.avatar = auth.info.image
      user.town = auth.info.location
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  private
  def current_user
    User.find_by_id(session[:current_user_id])
  end
  helper_method :current_user

  def require_user
    unless current_user
      redirect_to frustrations_url,
      alert: "You are not signed in"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :check_ownership, only: [:destroy, :update]

  def create
    frustration = Frustration.find(params[:frustration_id])
    @comment = frustration.comments.build(comment_params)
    @comment.user= current_user if current_user
    @comment.save

    respond_to do |format|
      format.html do
        redirect_to frustration
      end
      
      format.js do
        render
      end
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to comment.frustration
  end

  private
  def check_ownership
    @comment = Comment.find(params[:id])
    if @comment.user_id != current_user.id
      redirect_to frustrations_url,
      alert: "You can only delete own comments"
    end
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/frustrations_controller.rb
class FrustrationsController < ApplicationController

  before_filter :require_user, except: [:index, :show]
  before_filter :check_ownership, only: [:edit, :destroy, :update]

  def index
    @frustrations = Frustration.order("created_at DESC")
    @frustrations = Frustration.where('title LIKE ?', "%#{params[:q]}%").order('created_at DESC')
  end
  def show
    @frustration = Frustration.find(params[:id])
    @comment = @frustration.comments.build
  end

  def new
    @frustration = Frustration.new
  end
  def create
     @frustration = current_user.frustrations.build(frustration_params)
    if @frustration.save
      redirect_to frustrations_url,
        notice: "Frustration created successfully"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @frustration.update(frustration_params)
      redirect_to frustrations_url,
      notice: "Updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    @frustration.destroy
    redirect_to frustrations_url,
      notice: "Deleted successfully"
  end

  private
  def check_ownership
    @frustration = Frustration.find(params[:id])
    if @frustration.user_id != current_user.id
      redirect_to frustrations_url,
      alert: "You can only edit or delete own frustrations"
    end
  end
  def frustration_params 
    params.require(:frustration).permit(:title, :body, :cover)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create 
    if User.find_by_email(params[:email])
        if User.find_by_email(params[:email]) && User.find_by_email(params[:email]).authenticate(params[:password])
          session[:current_user_id] = User.find_by_email(params[:email]).id
        else
          redirect_to new_session_url, alert: "Authentication failed, please try again."
          return
        end
    else
        if User.from_omniauth(env["omniauth.auth"])
          session[:current_user_id] = User.from_omniauth(env["omniauth.auth"]).id
        else
        redirect_to new_session_url, alert: "Authentication failed, please try again."
        end
    end
    redirect_to root_url, notice: "Successfully Signed In"
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to frustrations_url,
    notice: "Successfully Signed Out"
  end

  def failure
    redirect_to root_url, alert: "Authentication failed, please try again."
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to frustrations_url, notice: "Welcome!"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).
      permit(:email, :password, :password_confirmation, :name, :avatar, :town)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frustrations_helper.rb
module FrustrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<article class="comment">
  <div class="pull-right">
    <%= button_to comment_path(comment),
      method: :delete,
      'data-confirm' => "Are you sure you want to delete this comment?" do %>
      <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
      <% end %>
  </div>
  <div>
    <%= simple_format comment.body %>
  </div>
  <footer><%= (comment.user ? comment.user.name : 'Anonymus') %></footer>
</article>

app/views/comments/create.js.erb
$('#comments').append("<%= escape_javascript(render @comment) %>");
$('#comment_body').val('');
$('#comment_author').val('');

app/views/frustrations/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <%= form_for(@frustration) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :required => true, placeholder: "Frustration Title", class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, :required => true, :placeholder=>'Frustration Text', class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.hidden_field(:cover_cache) %><br>
      <%= f.file_field(:cover) %>
      <p class="help-block">Upload a cover photo to your frustration</p>
    </div>

    <div>
      <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
    <% end %>
  </div>
</div>

app/views/frustrations/edit.html.erb
<h2>Edit Frustration</h2>

<%= render 'form' %>

app/views/frustrations/index.html.erb
<%= link_to "Frustration", new_frustration_path,class: 'btn btn-primary' %>

<div class="row" id="frustration_list">
  <% @frustrations.each_with_index do |frustration, i| -%>
    <div class="col-md-4 one_frustration">
      <div class="media">
        <div class="media-left">
          <%= link_to frustration_path(frustration) do %>
            <% unless frustration.cover_url.blank? %>
              <%= image_tag frustration.cover_url (:cover), alt: frustration.title, class: "media-object" %>
            <% else %>
              <%= image_tag('noimg.png', width: 100, class: "media-object") %>
            <% end %>
          <% end %>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><%= link_to frustration.title, frustration_path(frustration) %></h4>
          <%= simple_format frustration.body %><br>
          <% unless frustration.user.avatar_url.nil? %>
            <%= image_tag frustration.user.avatar_url(:glavatar) %>
          <% end %>
          <%= frustration.user.name %>,<br>
          <%#= frustration.created_at.to_s(:short) %>
          <%= frustration.created_at.strftime("%d %b at %H:%M") %>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/frustrations/new.html.erb
<h2>New Frustration</h2>

<%= render 'form' %>

app/views/frustrations/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <h1><%= @frustration.title %></h1>
      <p class="lead">
      by <% unless @frustration.user.avatar_url.nil? %>
        <%= image_tag @frustration.user.avatar_url(:glavatar) %>
      <% end %>
        <%= (@frustration.user.name) %>
      </p>

      <hr>

      <p><span class="glyphicon glyphicon-time"></span><%= (@frustration.created_at.strftime("%d %b at %H:%M")) %></p>

      <hr>
      <div>
        <% unless  @frustration.cover_url.nil?%>
          <%= image_tag(@frustration.cover_url, :class => "sljika", :alt => @frustration.title) %>
        <% end %>
      </div>
      <hr>
      
      <p class="lead"><%= simple_format(@frustration.body) %></p>

      <hr>
      <div>
        <%= link_to 'Edit', edit_frustration_path(@frustration),
              class: 'btn btn-default btn-xs' %>
        <%= button_to 'Delete', frustration_path(@frustration), method: :delete,
              class: 'btn btn-danger btn-xs',
              'data-confirm' => "Are you sure you want to delete this frustration '#{@frustration.title}'?" %>
      </div>

      <hr>

      <div class="well">
        <h4>Leave a Comment:</h4>
          <div class="form-group">
          <%= form_for [@frustration, @comment], remote: true do |f| %>
              <% if current_user %>
                <%= image_tag current_user.avatar_url(:glavatar) %>
              <% end %>
              <%= f.text_area :body, :class => "form-control"%>
            <%= f.submit %>
          <% end %>
          </div>
      </div>
  
      <hr>

      <div class="media">
        <div class="media-body">
          <div id="comments">
            <%= render @frustration.comments.select { |c| c.persisted? } %>
          </div>
        </div>
      </div>      
    </div>          
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Frustrations</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-59861550-1', 'auto');
      ga('send', 'pageview');
    </script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-invers6e" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Frustrations&#8482;</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li> <%= link_to "New Frustration", new_frustration_path %> </li>
            <% else %> 
              <li><%= link_to "Sign in", new_session_path %></li>
            <% end %>
          </ul>
            <%= form_tag frustrations_path, method: :get, class: 'navbar-form navbar-left', role: 'search' do %>
            <%= search_field_tag :q, params[:q], class: 'form-control', placeholder: "Search" %>
            <%= submit_tag "Search", class: 'btn btn-default' %>
            <% end %>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li>Signed in as: <strong><%= current_user.name %></strong> <%= image_tag current_user.avatar_url(:glavatar) %></li>
              <li><%= link_to 'Sign out', signout_path, id: "sign_out" %></li>
            <% else %>
              <li><%= link_to "Register", new_user_path %></li>
              <li><%= link_to "Sign in", new_session_path %></li>
              <li><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Menu <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Privacy Policy', privacy_path, id: "privacy" %></li>
                <li class="divider"></li>
                <li><%= link_to 'About us', about_path, id: "about" %></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid" id="contenat">
     <% flash.each do |key, msg| %>
      <div class="alert alert-<%= key == "alert" ? "danger" : "success" %>">
        <a class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
      <%= yield %>
    </div>
    <footer id="footer">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
           &copy; 1948 na 1949 &dash; Proleteri svih zemalja & co.
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/static_pages/about.html.erb
<h2 class="text-center">About Us...</h1><br>
  <div class="row">
    <div class="col-md-6">
      <h3 class="text-center">We're running drunk on Rails 4.2.0<br><small>in a very early alpha phase</small></h2>
      <%= image_tag('rails4.jpg', width: 300, class: "center-block", alt:"") %><br>
    </div>
    <div class="col-md-6">
      <h3 class="text-center">...with PostgreSQL</h2><br>
        <%= image_tag('postgresql.png', width: 150, class: "center-block", alt:"") %><br>
      <h4 class="text-center"> autovacuum launcher started</h4>
        <%= image_tag('autovacuum.gif', width: 200, class: "center-block", alt:"") %><br>
    </div>
  </div>

app/views/users/new.html.erb
<h2>Registration</h2>
<div class="row">
  <div class="col-md-6">
  <%= form_for(@user) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :required => true, placeholder: "Enter name", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :email%>
      <%= f.email_field :email, :required => true,  :placeholder=>'email address', :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, :required => true, placeholder: "Enter password", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, :required => true, placeholder: "Enter password again", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :Glavatar %>
      <%= f.file_field :avatar %>
      <p class="help-block">Upload a profile picture.</p>
    </div>

    <div>
      <%= f.submit "Register", class: "btn btn-primary btn-lg btn-block" %>
    </div>
 <% end %>
</div>
<div class="col-md-6">
   <h2> Or login with Facebook</h2>
    <br>
    <div>
      <%= link_to "Login with Facebook", "/auth/facebook", class: "btn btn-primary btn-lg btn-block" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h2>User</h2>

<h2>Name: <%= @user.name %></h2>
<h2>E-Mail: <%= @user.email.downcase %></h2>
<h2>Got frustrated first time: <%= @user.created_at %></h2>
<%= image_tag @user.avatar_url(:standard) %><br />